# Generated by Django 5.0 on 2024-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://www.eduversesummit.org/wp-content/uploads/2023/10/eduverse-logo-without-dates-420x323.png'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_image',
            field=models.URLField(default='https://www.eduversesummit.org/wp-content/uploads/2023/10/eduverse-logo-without-dates-420x323.png'),
        ),
    ]
