# Generated by Django 5.0 on 2024-01-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_author_alter_course_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='sector_image',
            new_name='sector_image_url',
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.URLField(),
        ),
    ]
