# Generated by Django 5.0 on 2024-01-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_comment_author_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
