# Generated by Django 5.0 on 2024-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='image_url',
            field=models.URLField(default='https://www.eduversesummit.org/wp-content/uploads/2023/10/eduverse-logo-without-dates-420x323.png'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
