# Generated by Django 5.0 on 2024-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_cart_author_cart_image_url_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
